inputs:
  ref_prompt: "A flower in a vase."
  base_prompt: "A flower in a vase."
  negative_prompt: ""
  custom_prompts:
    - "A <white_flower_1> <white_flower_2> in a <white_flower_1> <white_flower_2>."
    - "A <red_vase_1> <red_vase_2> in a <red_vase_1> <red_vase_2>."
  ref_image_path: "./sam_input/flower_vase.png" # TODO
  ref_mask_paths:
    - "./sam_output/flower_vase/flower_mask.png" # TODO
    - "./sam_output/flower_vase/vase_mask.png" # TODO
  init_mask_from_points: False
  mask_center_points: null
  init_image_path: ~
  init_mask_path: ~       
  edlora_paths:
    - "./experiments/ED-LoRA_ours/white_flower.pth" # TODO
    - "./experiments/ED-LoRA_ours/red_vase.pth" # TODO
  load_edlora: True
  lora_alpha: 0.7

outputs:
  outroot: "outputs_ours/prompt1/CI"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "./experiments/pretrained_models/chilloutmix" # TODO
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 200
  start_seed: 0
  batch_size: 4
  n_batches: 4
  verbose: True

attention_operations:
  attn_guidance_end: 0
  attn_guidance_interval: 1
  attn_guidance_weight: 10
  custom_attn_guidance_factor: 1.0

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]      
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]    

  mask_refinement_start: 60
  mask_refinement_end: 59
  mask_update_interval: 5
  mask_overlap_threshold: 0
  num_kmeans_init: 100
  rect_mask: False

  use_loss_mask: False
  visualization: True



