inputs:
  ref_prompt: "A cat wearing wearable glasses in a watercolor style."
  base_prompt: "A cat wearing wearable glasses in a <serene_watercolor_1> <serene_watercolor_2> style."
  negative_prompt: "girl, human, realistic"
  custom_prompts:
    - "A <gray_cat_1> <gray_cat_2> wearing <gray_cat_1> <gray_cat_2> in a <serene_watercolor_1> <serene_watercolor_2> style."
    - "A <wearable_glasses_1> <wearable_glasses_2> wearing <wearable_glasses_1> <wearable_glasses_2> in a <serene_watercolor_1> <serene_watercolor_2> style."
  ref_image_path: "sam_input/cat_glasses_watercolor.jpg"
  ref_mask_paths:
    - "sam_output/cat_glasses_watercolor/cat.png"
    - "sam_output/cat_glasses_watercolor/glasses.png"
  init_mask_from_points: False
  mask_center_points: 
    - [512, 512]
    - [356, 280]
  init_image_path: ~
  init_mask_path: ~       
  edlora_paths:
    - "experiments/EDLoRA_gray_cat_fuse_watercolor/models/edlora_model-latest.pth"
    - "experiments/EDLoRA_wearable_glasses_fuse_watercolor/models/edlora_model-latest.pth"
  load_edlora: True
  lora_alpha: 0.7

outputs:
  outroot: "outputs/prompt3/wo_la"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "experiments/composed_edlora/chilloutmix/serenewatercolor_chilloutmix/combined_model_base"
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 200
  start_seed: 0
  batch_size: 4
  n_batches: 4
  verbose: True

attention_operations:
  attn_guidance_end: 60
  attn_guidance_interval: 1
  attn_guidance_weight: 10
  custom_attn_guidance_factor: 1.0

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]      
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]    

  mask_refinement_start: 50
  mask_refinement_end: 80
  mask_update_interval: 5
  mask_overlap_threshold: 0
  num_kmeans_init: 100
  rect_mask: False

  use_loss_mask: False
  visualization: False



